### ISSUE TITLE
loads, but throws SSL warning

### ISSUE THREAD

**Issue by israelcurtis** [d03n3rfr1tz3/Bukkit.JSONAPI#1] opened 2015-06-25 05:51 UTC
your (much more updated) fork is loading nicely for me on 1.8.7 (and java 1.8.0_45 64bit), but just like the latest build of alecgorges' JSONAPI, it throws this SSL warning on boot.

`[23:28:28 WARN]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building 
failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to reque
sted target
[23:28:28 WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[23:28:28 WARN]: at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1937)
[23:28:28 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[23:28:28 WARN]: at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[23:28:28 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1478)
[23:28:28 WARN]: at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[23:28:28 WARN]: at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[23:28:28 WARN]: at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[23:28:28 WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1050)
[23:28:28 WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
[23:28:28 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
[23:28:28 WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
[23:28:28 WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[23:28:28 WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHtt
psURLConnection.java:185)
[23:28:28 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
[23:28:28 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
[23:28:28 WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.j
ava:254)
[23:28:28 WARN]: at java.net.URL.openStream(URL.java:1038)
[23:28:28 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer.connectionInfo(JSONServer.java:129)
[23:28:28 WARN]: at com.alecgorge.minecraft.jsonapi.JSONServer$1.run(JSONServer.java:107)
[23:28:28 WARN]: at java.lang.Thread.run(Thread.java:745)
[23:28:28 WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provi
der.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:28:28 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[23:28:28 WARN]: at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:230)
[23:28:28 WARN]: at sun.security.validator.Validator.validate(Validator.java:260)
[23:28:28 WARN]: at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[23:28:28 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[23:28:28 WARN]: at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[23:28:28 WARN]: at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1460)
[23:28:28 WARN]: ... 16 more
[23:28:28 WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certifi
cation path to requested target
[23:28:28 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[23:28:28 WARN]: at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131
)
[23:28:28 WARN]: at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[23:28:28 WARN]: at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[23:28:28 WARN]: ... 22 more`

**Comment by frdmn** [comment] 2015-06-25 06:40
@israelcurtis does the plugin work for you? Because I just tried @d03n3rfr1tz3's build and it loads indeed, but the actual API doesn't seem to work properly. Can't figure out why though. Nothing logged in the console.

**Comment by d03n3rfr1tz3** [comment] 2015-06-25 08:51
The problem is exactly as @electronicboy described it at the issue tracker at alecgorge/jsonapi/issues/442. Thanks to him. 

My fork just uses updated MC (and some changes here and there). So the website from which the IP adress gets pulled is still from @alecgorge and this one has a certificate from a CA, which is missing (or got dropped) in java.

I fixed it similarly by only adding the CA cert of that specific CA to my keystore, but completely forgot to write about it here.

**Comment by d03n3rfr1tz3** [comment] 2015-06-26 09:39
Closing this for now, because I believe in you ;-)

**Closed as completed by d03n3rfr1tz3** 2015-06-26 09:39 UTC
